name: gigapose
channels:
  - xformers
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - pip=24.0
  - python=3.9.6
  - pip:
    - torch>2.0
    - torchvision
    - omegaconf
    - torchmetrics==0.10.3
    - fvcore
    - iopath
    - xformers>=0.0.18
    - opencv-python 
    - pycocotools 
    - matplotlib 
    - onnxruntime 
    - onnx
    - scipy<1.13.0
    - ffmpeg
    - hydra-colorlog
    - hydra-core
    - gdown
    - pytorch-lightning==1.8.1
    - pandas
    - ruamel.yaml
    - pyrender
    - wandb
    - distinctipy
    - blenderproc